# Generated by Django 2.2 on 2019-04-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='memo',
            field=models.TextField(),
        ),
    ]
