# Generated by Django 2.2 on 2019-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190410_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
