# Generated by Django 2.2 on 2019-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_info_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
