# Generated by Django 2.2 on 2019-04-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190410_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(max_length=64, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='ip地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserGroup', verbose_name='用户组'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='user_type',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '高级用户')], default=0, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='caption',
            field=models.CharField(max_length=64, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user_info',
            field=models.ManyToManyField(to='blog.user_info', verbose_name='用户信息'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
