# Generated by Django 2.2 on 2019-04-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190410_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('avatar', models.FileField(upload_to='./upload/')),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
