# Generated by Django 2.2 on 2019-04-11 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播', 'verbose_name_plural': '轮播'},
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('220872dc-5c1b-11e9-9d34-509a4c2c7107'), max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
