# Generated by Django 2.2 on 2019-04-11 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190411_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('41852eb4-5c1b-11e9-a56e-509a4c2c7107'), max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
