# Generated by Django 2.2 on 2019-04-11 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190411_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.CharField(default=uuid.UUID('bc46553f-5c1c-11e9-98de-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.CharField(default=uuid.UUID('bc46553e-5c1c-11e9-b46b-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('bc460714-5c1c-11e9-8b77-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.CharField(default=uuid.UUID('bc462e28-5c1c-11e9-ba15-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default=uuid.UUID('bc460715-5c1c-11e9-abef-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
