# Generated by Django 2.2 on 2019-04-11 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190411_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('5b4c4486-5c21-11e9-8826-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
