# Generated by Django 2.2 on 2019-04-11 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190411_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('c0828fe8-5c23-11e9-a358-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
