# Generated by Django 2.2 on 2019-04-11 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190411_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='color_code',
            field=models.CharField(default='black', max_length=6),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('28124442-5c24-11e9-98fe-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
