# Generated by Django 2.2 on 2019-04-11 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190411_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='color_code',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('5c035bdc-5c24-11e9-80e1-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
