# Generated by Django 2.2 on 2019-04-11 15:12

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190411_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('34ee1dd4-5c29-11e9-b2fc-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='memo',
            field=tinymce.models.HTMLField(verbose_name='简介'),
        ),
    ]
