# Generated by Django 2.2 on 2019-04-11 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190411_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='id',
            field=models.CharField(default=uuid.UUID('52e903e2-5c29-11e9-a970-509a4c2c7107'), max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='memo',
            field=models.TextField(verbose_name='简介'),
        ),
    ]
